services:
  github-actions-tools:
    image: nikiakbar/my-docker-builder
    container_name: my-docker-builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Allows Docker commands within the container
    working_dir: /github/workspace