services:
  github-actions-tools:
    build:
      context: .
      dockerfile: Dockerfile # Make sure this matches the name of your Dockerfile
    container_name: github-actions-tools
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Allows Docker commands within the container
    working_dir: /github/workspace