name: Docker Build and Push to Docker Hub

on:
  push:
    branches:
      - main  # Or your main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: docker:20.10.21 # Use a specific docker image version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.12.1 # Use a specific Buildx version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile # Ensure this is the correct path to your Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/docker-builder:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/docker-builder:latest
